### ISSUE TITLE
How to even load local skins?

### ISSUE THREAD

**Issue by GhostOps77** [zatrit/openmcskins2#24] opened 2024-05-20 06:24 UTC
I can't find any proper documentation on how to do it. All i have done is added a local host, and i've put my skin's png into the `.minecraft/config/openmcskins/local/` directory. And all it did was load in some other skin that looks like a guy with a big moustache, in an armour (seems like a FALLBACK skin). Am i missing something here?

I use fabric loader, and MC version is 1.20.4

config file:
```toml
cacheTextures = true
verboseLogs = false
refreshOnConfigSave = true
loaderTimeout = 2.0
uuidMode = "OFFLINE"

[[hosts]]
type = "LOCAL"

[hosts.properties]
directory = "#{configDir}/openmcskins/local"

[[hosts]]
type = "MOJANG"

[[hosts]]
type = "FALLBACK"
```

**Comment by zatrit** [comment] 2024-05-20 07:13
Duplicate of #23

**Comment by GhostOps77** [comment] 2024-05-20 07:58
@zatrit I don't have any folder in any of those names (textures, metadata). I don't even have the skins folder

can u be more elaborate on the folder structure?

**Comment by zatrit** [comment] 2024-05-20 09:33
You can create them manually, but as soon as it becomes possible to work on the mod, I will implement their automatic creation

**Comment by GhostOps77** [comment] 2024-05-20 10:09
ok, now i've managed to load in my skin into the game. but i got an extra pants to it. how can i remove them?

![image](https://i.ibb.co/9sLXMCr/2024-05-20-15-32-33.png)

**Comment by GhostOps77** [comment] 2024-05-20 10:29
ok nvm, i have to restart minecraft for it to be gone
now its working good

**Closed as completed** 2024-05-20 10:29 UTC
